auto:     false
lsi:      false
pygments: true
safe:     false
server:   false
watch:    false

permalink: /:year/:month/:title/

markdown: pandoc
pandoc:
    extensions:
        - smart
        - standalone
        - mathjax
        - highlight-style: pygments

exclude: [".rvmrc", ".rbenv-version", ".gitignore", "config.ru", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "Procfile", "vendor"]
